from .BotUserNotAllowed import BotUserNotAllowedError
from .CannotRemoveUser import CannotRemoveUserError
from .ChannelType import ChannelTypeError
from .CharNameNotSet import CharNameNotSetError
from .ExceedsMaxLength import ExceedsMaxLengthError
from .HeightInput import HeightInputError
from .InsufficientPermissions import InsufficientPermissionsError
from .InvalidColor import InvalidColorError
from .NoAvailableUsersRemoval import NoAvailableUsersRemovalError
from .NoTrainingsError import NoTrainingsError
from .NotRegistered import NotRegisteredError
from .PositionExists import PositionExistsError
from .PositionNotFound import PositionNotFoundError
from .TooManyImages import TooManyImagesError
from .TooManyUsers import TooManyUsersError
from .Unauthorized import UnauthorizedError
from .VenueChannelNotSet import VenueChannelNotSetError
from .VenueDoesntExist import VenueDoesntExistError
from .VenueExists import VenueExistsError
from .VenuePendingApproval import VenuePendingApprovalError
################################################################################
